import type { AnalystProfile } from "./types";

export const analystProfiles: AnalystProfile[] = [
  {
    key: "gene_munster",
    name: "Gene Munster",
    username: "munster_gene",
    followerLabel: "X 팔로워 10만+",
    description:
      "AI·빅테크 성장주를 중심으로 실적, 투자 지출과 장기 성장 관점을 공유합니다.",
    focusAreas: ["AI 인프라", "빅테크", "반도체", "성장주"],
    sourceRole: "opinion",
    consensusEligible: true,
  },
  {
    key: "convequity",
    name: "Convequity",
    username: "Convequity",
    followerLabel: "X 팔로워 1만+",
    description:
      "AI 가치사슬 전반의 기술 구조와 병목을 기업 실적·밸류에이션에 연결해 분석합니다.",
    focusAreas: ["AI 인프라", "반도체", "데이터센터", "기업 소프트웨어"],
    sourceRole: "opinion",
    consensusEligible: true,
  },
  {
    key: "brian_stoffel",
    name: "Brian Stoffel",
    username: "Brian_Stoffel_",
    followerLabel: "X 팔로워 14만+",
    description:
      "기업 펀더멘털과 안티프래질 원칙을 바탕으로 장기 성장주 관점과 포트폴리오 판단을 공유합니다.",
    focusAreas: ["장기 성장주", "기업 펀더멘털", "밸류에이션", "포트폴리오"],
    sourceRole: "opinion",
    consensusEligible: true,
  },
  {
    key: "rihard_jarc",
    name: "Rihard Jarc",
    username: "RihardJarc",
    followerLabel: "X 팔로워 8만+",
    description:
      "테크·성장주 투자 논리와 보유 포지션을 명시하며 기업별 장기 관점을 공유합니다.",
    focusAreas: ["성장주", "빅테크", "AI", "포트폴리오"],
    sourceRole: "opinion",
    consensusEligible: true,
  },
  {
    key: "jonah_lupton",
    name: "Jonah Lupton",
    username: "JonahLupton",
    followerLabel: "X 팔로워 55만+",
    description:
      "중소형 성장주와 테마별 투자 아이디어를 근거·포지션·리스크와 함께 제시합니다.",
    focusAreas: ["중소형 성장주", "AI", "우주산업", "헬스케어"],
    sourceRole: "opinion",
    consensusEligible: true,
  },
  {
    key: "shay_boloor",
    name: "Shay Boloor",
    username: "StockSavvyShay",
    followerLabel: "X 팔로워 43만+",
    description:
      "장기 성장 가능성이 높은 산업과 성장주를 분석하며 공개 포트폴리오의 구성과 성과를 공유합니다.",
    focusAreas: ["AI 인프라", "반도체", "우주산업", "양자컴퓨팅", "사이버보안"],
    sourceRole: "opinion",
    consensusEligible: true,
  },
  {
    key: "serenity",
    name: "Serenity",
    username: "aleabitoreddit",
    followerLabel: "X 팔로워 99만+",
    description: "AI와 반도체 공급망을 중심으로 공개 투자 관점을 추적합니다.",
    focusAreas: ["AI 인프라", "반도체", "공급망"],
    sourceRole: "opinion",
    consensusEligible: true,
  },
  {
    key: "ryan_reeves",
    name: "Ryan Reeves",
    username: "RyanReeves_",
    followerLabel: "X 팔로워 5만+",
    description:
      "기업 펀더멘털과 성장 동인을 중심으로 직접적인 종목 관점과 리스크를 공유합니다.",
    focusAreas: ["성장주", "기업 펀더멘털", "AI", "소프트웨어"],
    sourceRole: "opinion",
    consensusEligible: true,
  },
  {
    key: "beth_kindig",
    name: "Beth Kindig",
    username: "Beth_Kindig",
    followerLabel: "X 팔로워 18만+",
    description:
      "AI·반도체·빅테크의 산업 데이터와 제3자 전망을 근거 소스로 정리합니다.",
    focusAreas: ["AI 인프라", "반도체", "빅테크", "클라우드"],
    sourceRole: "context",
    consensusEligible: false,
  },
  {
    key: "app_economy",
    name: "App Economy Insights",
    username: "EconomyApp",
    followerLabel: "X 팔로워 24만+",
    description:
      "디지털 경제와 상장 기술 기업의 실적·비즈니스 모델을 데이터와 시각화로 정리합니다.",
    focusAreas: ["디지털 경제", "빅테크", "SaaS", "실적 분석"],
    sourceRole: "context",
    consensusEligible: false,
  },
  {
    key: "dan_nystedt",
    name: "Dan Nystedt",
    username: "dnystedt",
    followerLabel: "X 팔로워 5만+",
    description:
      "반도체 공급망과 아시아 기술 산업의 수치·기업 발표를 빠르게 정리합니다.",
    focusAreas: ["반도체", "대만", "공급망", "기업 실적"],
    sourceRole: "context",
    consensusEligible: false,
  },
  {
    key: "tsoh_investing",
    name: "The Science of Hitting",
    username: "TSOH_Investing",
    followerLabel: "X 팔로워 6만+",
    description:
      "기업 리서치와 장기 투자 프레임을 공개 글과 뉴스레터 맥락으로 제공합니다.",
    focusAreas: ["기업 리서치", "장기 투자", "빅테크", "소비재"],
    sourceRole: "context",
    consensusEligible: false,
  },
  {
    key: "tae_kim",
    name: "Tae Kim",
    username: "firstadopter",
    followerLabel: "X 팔로워 10만+",
    description:
      "반도체와 기술 산업의 제품·수요·경쟁 구도를 업계 맥락과 함께 설명합니다.",
    focusAreas: ["반도체", "AI", "하드웨어", "기술 산업"],
    sourceRole: "context",
    consensusEligible: false,
  },
  {
    key: "dylan_patel",
    name: "Dylan Patel",
    username: "dylan522p",
    followerLabel: "X 팔로워 15만+",
    description:
      "AI 가속기, 반도체 제조와 데이터센터 경제성을 기술 산업 맥락으로 분석합니다.",
    focusAreas: ["AI 가속기", "반도체", "데이터센터", "공급망"],
    sourceRole: "context",
    consensusEligible: false,
  },
  {
    key: "chit_chat_stocks",
    name: "Chit Chat Stocks",
    username: "ChitChatStocks",
    followerLabel: "X 팔로워 1.8만+",
    description:
      "기업 인터뷰와 팟캐스트에서 장기 투자 아이디어와 추가 조사 단서를 발굴합니다.",
    focusAreas: ["팟캐스트", "기업 펀더멘털", "실적", "아이디어 발굴"],
    sourceRole: "context",
    consensusEligible: false,
  },
  {
    key: "stockmktnewz",
    name: "Evan (StockMKTNewz)",
    username: "StockMKTNewz",
    followerLabel: "X 팔로워 104만+",
    description:
      "미국 증시와 상장 기업의 주요 뉴스, 실적, 시장 이벤트를 빠르게 정리해 공유합니다.",
    focusAreas: ["미국 증시", "기업 뉴스", "실적", "시장 이벤트"],
    sourceRole: "news",
    consensusEligible: false,
  },
  {
    key: "space_investor",
    name: "SpaceInvestor",
    username: "SpaceInvestor_D",
    followerLabel: "X 팔로워 5만+",
    description:
      "우주 산업 기업의 계약, 발사, 규제와 시장 뉴스를 종목 탐색용으로 정리합니다.",
    focusAreas: ["우주산업", "방산", "계약", "시장 뉴스"],
    sourceRole: "news",
    consensusEligible: false,
  },
  {
    key: "muddy_waters",
    name: "Muddy Waters Research",
    username: "muddywatersre",
    followerLabel: "X 팔로워 25만+",
    description:
      "공매도 리서치와 기업 회계·지배구조 문제 제기를 독립 리스크 소스로 추적합니다.",
    focusAreas: ["공매도", "회계 리스크", "지배구조", "사기 의혹"],
    sourceRole: "risk",
    consensusEligible: false,
  },
  {
    key: "stock_jabber",
    name: "StockJabber",
    username: "StockJabber",
    followerLabel: "X 팔로워 11만+",
    description:
      "상장 기업의 공시, 프로모션과 잠재적 레드 플래그를 비판적 관점에서 추적합니다.",
    focusAreas: ["공시", "프로모션 리스크", "소형주", "레드 플래그"],
    sourceRole: "risk",
    consensusEligible: false,
  },
  {
    key: "kerrisdale_capital",
    name: "Kerrisdale Capital",
    username: "KerrisdaleCap",
    followerLabel: "X 팔로워 9만+",
    description:
      "공개 롱·숏 리서치를 통해 밸류에이션, 사업 모델과 하방 리스크를 검증합니다.",
    focusAreas: ["공매도", "밸류에이션", "사업 모델", "하방 리스크"],
    sourceRole: "risk",
    consensusEligible: false,
  },
];
